### ISSUE TITLE
segmentation fault on Raspbian Buster

### ISSUE THREAD

**Issue by mpalyga** [lrybak/domoticz-airly#8]
hej
  following the upgrade to Buster on Raspbian, domoticz is failing with segemnantion fault, see log:
2019-07-02 22:45:34.893  Error: Thread 4 (Thread 0x74d98220 (LWP 24290)):
2019-07-02 22:45:34.893  Error: #0  __waitpid (options=0, stat_loc=0x74d958b8, pid=24316) at ../sysdeps/unix/sysv/linux/waitpid.c:30
2019-07-02 22:45:34.893  Error: #1  __waitpid (pid=24316, stat_loc=0x74d958b8, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:25
2019-07-02 22:45:34.893  Error: #2  0x00112a10 in dumpstack_gdb(bool) ()
2019-07-02 22:45:34.893  Error: #3  0x00112ffc in signal_handler(int, siginfo_t*, void*) ()
2019-07-02 22:45:34.893  Error: #4  <signal handler called>
2019-07-02 22:45:34.893  Error: #5  raise (sig=11) at ../sysdeps/unix/sysv/linux/raise.c:50
2019-07-02 22:45:34.893  Error: #6  <signal handler called>
2019-07-02 22:45:34.893  Error: #7  0x76de1a1c in __pthread_rwlock_wrlock_full (abstime=0x0, rwlock=0x0) at pthread_rwlock_common.c:576
2019-07-02 22:45:34.893  Error: #8  __GI___pthread_rwlock_wrlock (rwlock=0x0) at pthread_rwlock_wrlock.c:27
2019-07-02 22:45:34.893  Error: #9  0x6925fd58 in CRYPTO_THREAD_write_lock () from /usr/lib/arm-linux-gnueabihf/libcrypto.so.1.1
2019-07-02 22:45:34.894  Error: #10 0x6928bf40 in ?? () from /usr/lib/arm-linux-gnueabihf/libcrypto.so.1.1
Segmentation fault

as per some analisys, issue is purly related to this plugin - see [domoticz forum post ](https://www.domoticz.com/forum/viewtopic.php?f=6&t=28562&p=218589#p218487)

I've tried a little to analyze the code of plugin .. but no time for deeper investigation... 

mozesz pomoc Kolego :) 

pozdr
  m. 

PS. Airly is one of the important plugin, lovely working to provide data from system during bad air in the world

**Comment by lrybak** [comment]
Sorry to say that Kolego but I have no time to concentrate on this. 
Tool is using standard python http client. Not sure if I can do anything here. Domoticz and it's plugin system it's not very reliable.
That's why I decided to abandon it and move my system to Home Assistant.

Please consider to downgrade to stretch. I hear a lot of complain about Domoticz running on buster

Ps. Sorry for very late response.
